"use client";
import {useEffect,useState} from 'react';
import {getStoredSession,publicFileUrl,rest,uploadPublicFile} from '@/lib/supabase-browser';
type Contestant={id:string;public_name:string|null;biography:string|null;scripture:string|null;platform:string|null;headshot_public_path:string|null;campaign_video_url:string|null;public_profile_status:string};
const clean=(name:string)=>name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/^-|-$/g,'');
export function CampaignProfileEditor(){
 const [profile,setProfile]=useState<Contestant|null>(null),[name,setName]=useState(''),[bio,setBio]=useState(''),[scripture,setScripture]=useState(''),[platform,setPlatform]=useState(''),[headshot,setHeadshot]=useState<File|null>(null),[video,setVideo]=useState<File|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void(async()=>{const session=getStoredSession();if(!session){setMessage('Please sign in to open your contestant workspace.');return;}const result=await rest<Contestant[]>(`pgws_contestants?user_id=eq.${session.user.id}&select=*&limit=1`);const row=result.data?.[0]??null;if(!row){setMessage('This workspace opens after competition staff accepts your application.');return;}setProfile(row);setName(row.public_name||'');setBio(row.biography||'');setScripture(row.scripture||'');setPlatform(row.platform||'');})();},[]);
 async function submit(){const session=getStoredSession();if(!session||!profile)return;setBusy(true);setMessage('Uploading and saving your profile...');let headshotPath=profile.headshot_public_path||'';let videoUrl=profile.campaign_video_url||'';
  if(headshot){headshotPath=`${session.user.id}/profile/${Date.now()}-${clean(headshot.name)}`;const uploaded=await uploadPublicFile(headshotPath,headshot);if(uploaded.error){setBusy(false);setMessage(uploaded.error);return;}}
  if(video){const videoPath=`${session.user.id}/campaign/${Date.now()}-${clean(video.name)}`;const uploaded=await uploadPublicFile(videoPath,video);if(uploaded.error){setBusy(false);setMessage(uploaded.error);return;}videoUrl=publicFileUrl(videoPath);}
  const saved=await rest<Contestant[]>('rpc/pgws_save_contestant_profile',{method:'POST',body:JSON.stringify({p_public_name:name,p_biography:bio,p_scripture:scripture,p_platform:platform,p_headshot_public_path:headshotPath,p_campaign_video_url:videoUrl})});setBusy(false);if(saved.error){setMessage(saved.error);return;}setProfile(saved.data?.[0]??profile);setMessage('Profile submitted for staff review. It will not appear publicly until staff approves it.');setHeadshot(null);setVideo(null);
 }
 if(!profile)return <div className="panel"><h2>Campaign profile access</h2><p>{message||'Loading your accepted-contestant record...'}</p></div>;
 return <div className="campaign-editor"><section className="panel"><div className="record-heading"><div><p className="eyebrow">PUBLIC PROFILE</p><h2>Your story for donors</h2></div><span className="status">{profile.public_profile_status.replace(/_/g,' ')}</span></div><div className="notice"><span>◆</span><div><strong>Staff-reviewed publication</strong><br/>Saving sends the profile back to staff review, including later edits to a previously published profile.</div></div>{message&&<p className="notice" role="status">{message}</p>}<div className="form-grid"><label className="field"><span>Public name</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field field--wide"><span>Biography</span><textarea rows={7} value={bio} onChange={e=>setBio(e.target.value)} placeholder="Share your story, leadership, service, and why this scholarship matters." required/><small>{bio.length} characters · minimum 40</small></label><label className="field field--wide"><span>Campaign platform</span><textarea rows={5} value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="What cause will you champion?"/></label><label className="field field--wide"><span>Signature scripture</span><input value={scripture} onChange={e=>setScripture(e.target.value)} placeholder="Example: Proverbs 31:10"/></label><label className="field"><span>Official public headshot</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setHeadshot(e.target.files?.[0]||null)}/><small>JPG, PNG, or WebP. Portrait orientation works best.</small></label><label className="field"><span>Campaign video</span><input type="file" accept="video/mp4,video/quicktime" onChange={e=>setVideo(e.target.files?.[0]||null)}/><small>MP4 or MOV, up to 250 MB.</small></label></div><button className="button button--lipstick" disabled={busy||name.trim().length<2||bio.trim().length<40} onClick={submit}>{busy?'Saving...':'Submit profile for staff review'}</button></section></div>;
}
