"use client";
import{useCallback,useEffect,useState}from"react";import Link from"next/link";import{createPrivateFileUrl,getStoredSession,rest}from"@/lib/supabase-browser";
type RecordData={id:string;user_id:string;status:string;completion_percent:number;agreement_status:string;answers:Record<string,unknown>;submitted_at:string|null;updated_at:string};
type Profile={legal_name:string|null;preferred_name:string|null;email:string|null;phone:string|null;college:string|null;email_verified:boolean};
type AppFile={id:string;field_key:string;object_path:string;original_name:string;content_type:string|null;review_status:string;url?:string};
type Contestant={id:string;public_profile_status:string;public_name:string|null};
const statuses=['submitted','under_review','correction_requested','waitlisted','accepted','declined'] as const;
const rubric=[['application_quality','Application quality',15],['faith_and_mission','Faith and mission alignment',20],['leadership','Leadership',20],['service','Service',20],['platform','Platform and advocacy',15],['communication','Communication',10]] as const;
export function ApplicationRecord({id}:{id:string}){
 const[data,setData]=useState<RecordData|null>(null),[profile,setProfile]=useState<Profile|null>(null),[files,setFiles]=useState<AppFile[]>([]),[contestant,setContestant]=useState<Contestant|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[panel,setPanel]=useState<'correction'|'note'|'rubric'|null>(null),[reason,setReason]=useState(''),[status,setStatus]=useState('under_review'),[note,setNote]=useState(''),[recommendation,setRecommendation]=useState('accept'),[scores,setScores]=useState<Record<string,number>>({});
 const load=useCallback(async()=>{const session=getStoredSession();if(!session){setMessage('Staff sign-in required.');return;}const roles=await rest<{role:string}[]>(`pgws_user_roles?user_id=eq.${session.user.id}&active=eq.true&select=role`);if(!roles.data?.some(r=>['reviewer','competition_admin','super_admin'].includes(r.role))){setMessage('Your account is not authorized to open applicant records.');return;}const app=await rest<RecordData[]>(`pgws_applications?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);const row=app.data?.[0]??null;setData(row);if(!row){setMessage(app.error||'Application not found.');return;}setStatus(row.status);const[p,f,c]=await Promise.all([rest<Profile[]>(`pgws_profiles?user_id=eq.${row.user_id}&select=legal_name,preferred_name,email,phone,college,email_verified&limit=1`),rest<AppFile[]>(`pgws_application_files?application_id=eq.${row.id}&select=id,field_key,object_path,original_name,content_type,review_status&order=uploaded_at.desc`),rest<Contestant[]>(`pgws_contestants?application_id=eq.${row.id}&select=id,public_profile_status,public_name&limit=1`)]);setProfile(p.data?.[0]??null);setContestant(c.data?.[0]??null);const withUrls=await Promise.all((f.data||[]).map(async file=>{const signed=await createPrivateFileUrl(file.object_path);return{...file,url:signed.data?.signedURL};}));setFiles(withUrls);setMessage(app.error||'');},[id]);
 useEffect(()=>{void load();},[load]);
 async function run(path:string,body:Record<string,unknown>,success:string){setBusy(true);setMessage('');const result=await rest(path,{method:'POST',body:JSON.stringify(body)});setBusy(false);if(result.error){setMessage(result.error);return;}setMessage(success);setPanel(null);setReason('');setNote('');await load();}
 async function changeStatus(){await run('rpc/pgws_staff_update_application_status',{p_application_id:id,p_status:status,p_reason:reason},`Status updated to ${status.replace(/_/g,' ')}.`);}
 async function correction(){await run('rpc/pgws_staff_request_correction',{p_application_id:id,p_message:reason,p_fields:[]},'Correction request recorded and the applicant may edit her application.');}
 async function addNote(){await run('rpc/pgws_staff_add_note',{p_application_id:id,p_body:note,p_visibility:'competition_admin'},'Private note saved.');}
 async function saveReview(){await run('rpc/pgws_staff_save_review',{p_application_id:id,p_scores:scores,p_recommendation:recommendation,p_reason:reason},'Review rubric saved to the audit record.');}
 async function publishProfile(){if(!contestant)return;await run('rpc/pgws_staff_publish_profile',{p_contestant_id:contestant.id,p_publish:contestant.public_profile_status!=='published',p_reason:reason},contestant.public_profile_status==='published'?'Public profile hidden.':'Public contestant profile published.');}
 if(!data&&!message)return <div className="panel">Loading protected applicant record…</div>;
 if(!data)return <div className="notice">{message}</div>;
 return <>
 <section className="panel"><div className="record-heading"><div><p className="eyebrow">APPLICANT</p><h2>{profile?.legal_name||profile?.preferred_name||'Applicant record'}</h2><p>{profile?.college} · {profile?.email}<br/>{profile?.email_verified?'Verified email':'Verification pending'}</p></div><div><span className="status">{data.status.replace(/_/g,' ')}</span><p>{data.completion_percent}% complete<br/>{data.agreement_status} agreement</p></div></div></section>
 {message&&<div className="notice" role="status" style={{marginBottom:18}}>{message}</div>}
 <section className="panel"><h2>Submitted photos and files</h2>{files.length?<div className="admin-file-grid">{files.map(file=><article key={file.id}><div className="admin-file-preview">{file.url&&file.content_type?.startsWith('image/')?<img src={file.url} alt={file.field_key.replace(/_/g,' ')}/>:file.url&&file.content_type?.startsWith('video/')?<video src={file.url} controls preload="metadata"/>:<span>PRIVATE FILE</span>}</div><b>{file.field_key.replace(/_/g,' ')}</b><small>{file.original_name} · {file.review_status}</small>{file.url&&<a className="button button--paper button--small" href={file.url} target="_blank" rel="noreferrer">Open full file ↗</a>}</article>)}</div>:<p>No uploaded files are attached to this application.</p>}</section>
 <section className="panel"><h2>Application responses</h2><div className="form-grid">{Object.entries(data.answers||{}).map(([key,value])=><div className="field field--wide" key={key}><label>{key.replace(/_/g,' ')}</label><div className="response-box">{typeof value==='boolean'?(value?'Yes':'No'):String(value||'—')}</div></div>)}</div></section>
 <section className="panel"><h2>Decision and publication</h2><div className="notice"><span>◆</span><div>Every decision requires a reason and is written to the permanent audit log.</div></div><div className="decision-grid"><label className="field"><span>Application status</span><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(value=><option key={value} value={value}>{value.replace(/_/g,' ')}</option>)}</select></label><label className="field field--wide"><span>Required reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why this action is being taken."/></label></div><div className="hero-actions"><button disabled={busy||reason.trim().length<5} className="button button--lipstick" onClick={changeStatus}>Save status decision</button>{contestant&&<button disabled={busy||reason.trim().length<5} className="button button--ink" onClick={publishProfile}>{contestant.public_profile_status==='published'?'Hide public profile':'Publish public profile'}</button>}</div>{contestant&&<p className="field-help">Profile status: {contestant.public_profile_status}. Contestants manage their public story and campaign video from their portal; staff controls publication.</p>}</section>
 <section className="panel"><h2>Review actions</h2><div className="hero-actions"><button className="button button--paper" onClick={()=>setPanel(panel==='correction'?null:'correction')}>Request correction</button><button className="button button--paper" onClick={()=>setPanel(panel==='note'?null:'note')}>Add private note</button><button className="button button--lipstick" onClick={()=>setPanel(panel==='rubric'?null:'rubric')}>Open review rubric</button></div>
 {panel==='correction'&&<div className="action-panel"><h3>Request a correction</h3><p>Tell the applicant exactly what needs attention. Her status will change to correction requested.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the correction needed."/><button disabled={busy||reason.trim().length<10} className="button button--lipstick" onClick={correction}>Send correction request</button></div>}
 {panel==='note'&&<div className="action-panel"><h3>Add a private staff note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="This note is never shown publicly."/><button disabled={busy||note.trim().length<5} className="button button--lipstick" onClick={addNote}>Save private note</button></div>}
 {panel==='rubric'&&<div className="action-panel"><h3>2027 application review rubric</h3><div className="rubric-grid">{rubric.map(([key,label,max])=><label key={key}><span>{label} / {max}</span><input type="number" min="0" max={max} value={scores[key]??''} onChange={e=>setScores(old=>({...old,[key]:Number(e.target.value)}))}/></label>)}</div><label className="field"><span>Recommendation</span><select value={recommendation} onChange={e=>setRecommendation(e.target.value)}><option value="accept">Accept</option><option value="waitlist">Waitlist</option><option value="decline">Decline</option><option value="needs_correction">Needs correction</option></select></label><label className="field"><span>Required review reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<5} className="button button--lipstick" onClick={saveReview}>Save completed review</button></div>}
 </section><Link href="/admin/applications">← Back to applicants</Link></>;
}
