"use client";
import Link from "next/link";import { useEffect,useState } from "react";import { getStoredSession,rest } from "@/lib/supabase-browser";
type Application={id:string;status:string;completion_percent:number;agreement_status:string;updated_at:string};
export function PortalClient(){const [loading,setLoading]=useState(true);const [application,setApplication]=useState<Application|null>(null);const [error,setError]=useState('');const session=getStoredSession();
  useEffect(()=>{async function load(){if(!session){setLoading(false);return;}const result=await rest<Application[]>(`pgws_applications?user_id=eq.${session.user.id}&select=id,status,completion_percent,agreement_status,updated_at&limit=1`);if(result.error&&result.status!==404)setError(result.error);setApplication(result.data?.[0]??null);setLoading(false);}load();},[session?.user.id]);
  if(loading)return <div className="panel">Loading your secure workspace…</div>;
  if(!session)return <div className="panel"><h2>Please sign in</h2><p>Your application and documents are private.</p><Link className="button button--lipstick" href="/login">Sign in</Link></div>;
  const completion=application?.completion_percent??0;const status=application?.status??'Draft not started';
  return <><div className="notice notice--success"><span>◆</span><div><strong>Signed in as {session.user.email}</strong><br />Your account keeps one continuous record from applicant to contestant—no second account needed if you are selected.</div></div>{error&&<div className="notice" style={{marginTop:16}}>{error}</div>}
  <div className="stat-grid" style={{marginTop:24}}><div className="stat-card"><strong>{completion}%</strong><span>application complete</span></div><div className="stat-card"><strong>{application?.agreement_status==='signed'?'15':'0'}/15</strong><span>required initials</span></div><div className="stat-card"><strong>{status}</strong><span>current status</span></div><div className="stat-card"><strong>ET</strong><span>official timezone</span></div></div>
  <section className="panel"><p className="eyebrow">YOUR NEXT STEP</p><h2>{application?'Continue your application':'Begin your application'}</h2><p>Complete all seven sections, upload your public-profile materials, read the entire agreement, and review every deadline before submitting.</p><div className="hero-actions"><Link className="button button--lipstick" href="/application">Open application</Link><Link className="button button--paper" href="/agreement">Read & sign agreement</Link></div></section>
  <section className="panel"><h2>Your competition workspace</h2><div className="editorial-grid" style={{marginTop:18}}><article className="editorial-card" data-number="01"><h3>Application</h3><p>Seven sections, saved drafts, private uploads, and submission review.</p><Link href="/application">Open application →</Link></article><article className="editorial-card" data-number="02"><h3>Agreement</h3><p>42 numbered sections, 15 initials, 21 acknowledgments, and electronic signature.</p><Link href="/agreement">Open agreement →</Link></article><article className="editorial-card editorial-card--accent" data-number="03"><h3>Messages & calendar</h3><p>Official announcements and contestant tasks appear here after staff activates them.</p><Link href="/timeline">View public timeline →</Link></article></div></section></>;
}
