"use client";
import Link from "next/link";import{useEffect,useState}from"react";import{getStoredSession,rest}from"@/lib/supabase-browser";
type Role={role:string;active:boolean};type Application={id:string;user_id:string;status:string;completion_percent:number;agreement_status:string;submitted_at:string|null;updated_at:string};
export function AdminClient(){const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[applications,setApplications]=useState<Application[]>([]);const[error,setError]=useState('');const session=getStoredSession();
useEffect(()=>{async function load(){if(!session){setLoading(false);return;}const roles=await rest<Role[]>(`pgws_user_roles?user_id=eq.${session.user.id}&active=eq.true&select=role,active`);const ok=Boolean(roles.data?.some(r=>['reviewer','competition_admin','finance_admin','super_admin'].includes(r.role)));setAuthorized(ok);if(ok){const apps=await rest<Application[]>('pgws_applications?select=id,user_id,status,completion_percent,agreement_status,submitted_at,updated_at&order=updated_at.desc');if(apps.error)setError(apps.error);setApplications(apps.data??[]);}else if(roles.error)setError(roles.error);setLoading(false);}load();},[session?.user.id]);
if(loading)return <div className="panel">Checking your approved staff role…</div>;if(!session)return <div className="panel"><h2>Staff sign-in required</h2><Link className="button button--lipstick" href="/admin/login">Staff sign in</Link></div>;if(!authorized)return <div className="panel"><h2>Access not assigned</h2><p>Your account is signed in, but it does not have an active PGWS staff role. Administrative access is tied to your verified user ID—not just an email address.</p><a className="button button--ink" href="mailto:nationals@estherfundsinc.org?subject=PGWS%20staff%20access">Request staff activation</a></div>;
const submitted=applications.filter(a=>a.submitted_at).length;const ready=applications.filter(a=>a.agreement_status==='signed').length;
return <>{error&&<div className="notice">{error}</div>}<div className="stat-grid"><div className="stat-card"><strong>{applications.length}</strong><span>total applicants</span></div><div className="stat-card"><strong>{submitted}</strong><span>submitted applications</span></div><div className="stat-card"><strong>{ready}</strong><span>signed agreements</span></div><div className="stat-card"><strong>{applications.filter(a=>a.status==='accepted').length}</strong><span>accepted contestants</span></div></div><section className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'center'}}><div><p className="eyebrow">APPLICATION REVIEW</p><h2>All applicant records</h2></div><button className="button button--paper button--small">Export authorized CSV</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Applicant ID</th><th>Status</th><th>Progress</th><th>Agreement</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{applications.length?applications.map(app=><tr key={app.id}><td>{app.id.slice(0,8)}…</td><td><span className="status">{app.status}</span></td><td>{app.completion_percent}%</td><td><span className={`status ${app.agreement_status==='signed'?'status--green':''}`}>{app.agreement_status}</span></td><td>{app.submitted_at?new Date(app.submitted_at).toLocaleDateString():'—'}</td><td><Link href={`/admin/applications/${app.id}`}>Open →</Link></td></tr>):<tr><td colSpan={6}>No applicant records yet. New verified accounts will appear after the database migration is connected.</td></tr>}</tbody></table></div></section></>;
}
